server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: profitsoft_2
  profiles:
    active:
      - dev
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

kafka:
  topics:
    books: ${KAFKA_TOPICS_BOOKS:books}

cors:
  allowed:
    methods: GET,POST,PUT,DELETE
    headers: '*'
    credentials: true

pagination:
  default:
    page: 0
    size: 10
    sort: 'id, asc'