spring:
  datasource:
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:h2:mem:book_db}
    driver-class-name: 'org.h2.Driver'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true