server:
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    key-store: ${SERVER_SSL_KEYSTORE_PATH:classpath:httpsKey.p12}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:4718da7d57e62178e0605b08cfd69428957a5128ee5ef7b5ff9e76b7db6520df}
    key-password: ${SERVER_SSL_KEY_PASSWORD:4718da7d57e62178e0605b08cfd69428957a5128ee5ef7b5ff9e76b7db6520df}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SERVER_SSL_KEY_ALIAS:httpsKey}

spring:
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/book_db}
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: true

cors:
  allowed:
    origins: '*'

logging:
  level:
    com.melnyk.profitsoft_2: debug