server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: profitsoft_2
  profiles:
    active:
      - dev

cors:
  allowed:
    methods: GET,POST,PUT,DELETE
    headers: '*'
    credentials: true

pagination:
  default:
    page: 0
    size: 10
    sort: 'id, asc'