spring:
  datasource:
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:h2:mem:book_db}
    driver-class-name: 'org.h2.Driver'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: true

kafka:
  topics:
    books: ${KAFKA_TOPICS_BOOKS:books}

logging:
  level:
    com.melnyk.profitsoft_2: debug