spring:
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/book_db}
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: true

cors:
  allowed:
    origins: '*'
    methods: GET,POST,PUT,DELETE
    credentials: true

logging:
  level:
    com.melnyk.profitsoft_2: debug